services:
  - type: web
    name: admin-backend  # Descriptive name
    env: python
    buildCommand: "pip install -r requirements.txt"  # Install dependencies
    startCommand: "gunicorn backend.backend.wsgi:application"  # Command to start the app
    plan: free
