# Generated by Django 5.0.7 on 2024-07-23 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogpost", "0003_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
