# Generated by Django 5.0.7 on 2024-08-03 05:48

import blogpost.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogpost", "0004_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif"]
                    ),
                    blogpost.validators.validate_image_size,
                ],
            ),
        ),
    ]
